default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: "123456789123456789123456789123456789123456789123456789123456789"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
